spring.application.name=

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=
spring.jpa.properties.hibernate.show_sql=
spring.jpa.properties.hibernate.jdbc.batch_size=
spring.jpa.properties.hibernate.order_inserts=
spring.jpa.properties.hibernate.order_updates=

spring.jpa.properties.hibernate.dialect=

springdoc.swagger-ui.path=
spring.jackson.default-property-inclusion=

jwt.access.private=
jwt.access.public=
jwt.access.expires-in-minutes=

jwt.refresh.private=
jwt.refresh.public=
jwt.refresh.expires-in-minutes=

minio.endpoint=
minio.access-key=
minio.secret-key=
minio.bucket-name=

stripe.psh-key=
stripe.sct-key=
stripe.wh-sct=

ghn.token=
ghn.shop-id=