spring.application.name=bookstore-api

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/api-docs

jwt.access.private=
jwt.access.public=
jwt.access.expires-in-minutes=